[build]
  command = "npm run build"             # ✅ Exécute vike build
  publish = "dist/client"              # ✅ Cible les fichiers générés
  functions = "netlify/functions"      # ✅ Cible le dossier de tes fonctions Netlify

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"       # ✅ Redirige tout vers ta fonction SSR
  status = 200
